"""
Provides interface to join objects generated by ConfigSpec
to Nipype ReportCapableInterface

Provides the niviz.view_adapter.factory object which can be used register and
create interfaces
"""

from __future__ import annotations
from typing import TYPE_CHECKING, Optional
if TYPE_CHECKING:
    from nipype.interfaces.mixins import reporting

from pathlib import Path
from string import Template
from dataclasses import dataclass, InitVar

import logging
import logging.config

logging.config.fileConfig("logging.conf")
logger = logging.getLogger(__name__)


@dataclass
class ArgInputSpec:
    '''
    Store configuration options and method key for constructing
    Nipype ReportCapableInterface classes

    Args:
        out_path: Template string for building output path
        bids_entities: BIDS entities (key,value) paired tuples

    Attributes:
        name: Name of SVG report being generated
        method: Method key for to select which
            `reporting.ReportCapableInterface` to select
        interface_args: Dictionary of **kwargs to pass to
            `reporting.ReportCapableInterface`
        bids_output: Path to target SVG output
    '''
    out_path: InitVar[str]
    bids_entities: InitVar[tuple[tuple[str, str]]]

    name: str
    method: str
    interface_args: dict
    bids_output: Path = None

    def __post_init__(self, out_path, bids_entities):
        '''
        Construct final output path

        Raises:
            KeyError if BIDS entities required for output_path are missing
        '''

        self.bids_output = Path(
            Template(out_path).substitute({x[0]: x[1]
                                           for x in bids_entities}))


class RPTFactory(object):
    '''
    Factory class to generate Nipype RPT nodes
    given argument specification objects derived
    from niviz

    Attributes:
        _interfaces: Mapping method strings to
            `reporting.ReportCapableInterface` subclass
    '''

    _interfaces: dict[str, reporting.ReportCapableInterface]

    def __init__(self):
        self._interfaces = {}

    def get_interface(self,
                      spec: ArgInputSpec) -> reporting.ReportCapableInterface:
        '''
        Retrieve and configure interface from registered list

        Args:
            spec: Input specification for generating SVG image

        Returns:
            interface: Configured `reporting.ReportCapableInterface`
        '''

        try:
            interface_class = self._interfaces[spec.method]
        except KeyError:
            logger.error(
                f"View method {spec.method} has not been registered "
                "with RPTFactory. If using a custom ReportCapableInterface"
                " register to RPTFactory using\n"
                "from view_adapter import register_interface\n"
                f"register_interface(ReportCapableInterface, {spec.method})")
            raise

        # Create and configure node args
        interface = interface_class(**spec.argmap)
        interface.outputs.out_report = spec.bids_output
        return interface

    def register_interface(self,
                           rpt_interface: reporting.ReportCapableInterface,
                           method: str,
                           override: Optional[bool] = False) -> None:
        '''
        Register a RPT to enable creation with factory_method()

        Args:
            rpt_interface: `reporting.ReportCapableInterface` subclass
            method: String key for accessing interface
            override: Override an existing key if it exists

        Raises:
            KeyError: If method key already exists for another Interface
        '''

        if (method not in self._interfaces) or override:
            self._interfaces[method] = rpt_interface
        else:
            logger.error(
                f"Method already registered as {self._interfaces[method]}. "
                " Use override=True to replace existing method key")
            raise KeyError
        return

    def view_interfaces(self) -> dict[str, reporting.ReportCapableInterface]:
        '''
        Return a mapping of currently registered interfaces

        Returns:
            registered_interfaces: Dictionary of registered interfaces
        '''
        return self._interfaces


def register_interface(rpt_interface: reporting.ReportCapableInterface,
                       method: str) -> None:
    '''
    Helper function to register a ReportCapableInterface to the persistent
    RPTFactory instance.

    Calls RPTFactory().register_interface(*args)

    Args:
        rpt_interface: Nipype ReportCapableInterface class
        method: String key for accessing Interface

    Raises:
        KeyError: If method key already exists for another Interface
    '''
    factory.register_interface(rpt_interface, method)


factory = RPTFactory()


# Avoid circular import problem
def initialize_defaults():
    import niviz.interfaces.views
    niviz.interfaces.views._run_imports()


def get_interfaces_from_specs(
        arg_specs: list[ArgInputSpec]) -> reporting.ReportCapableInterface:
    '''
    Generate Nipype ReportCapableInterfaces from a list of
    ArgInputSpecs

    Args:
        arg_specs:  Iterable of ArgInputSpecs containing instructions for
        building visualization interfaces

    Returns:
        Iterable of Nipype ReportCapableInterfaces
    '''
    return [factory.get_interface(a) for a in arg_specs]


initialize_defaults()
